package com.iqbal.trashbank.helper

class Constant {
    companion object{
        val PREF_ID_USER = "PREF_ID_USER"
        val PREF_ID_ROLE = "PREF_ID_ROLE"
        val PREF_ROLE_NAME = "PREF_ROLE_NAME"
        val PREF_NAMA = "PREF_NAMA"
        val PREF_TELEPON = "PREF_TELEPON"
        val PREF_SALDO = "PREF_SALDO"

        val PREF_ID_JP = "PREF_ID_JP"
        val PREF_TANGGAL_JP = "PREF_TANGGAL_JP"

        val PREF_ID_TRANSAKSI = "PREF_ID_TRANSAKSI"
        val PREF_NOMINAL = "PREF_NOMINAL"
        val PREF_ID_JADWALPENGAMBILAN = "PREF_ID_JADWALPENGAMBILAN"
        val PREF_ID_MASYARAKAT = "PREF_ID_MASYARAKAT"
        val PREF_NAMA_TRANSAKSI = "PREF_NAMA_TRANSAKSI"

        val PREF_ID_PENGAJUAN = "PREF_ID_PENGAJUAN"
        val PREF_Status_Pengajuan = "PREF_Status_Pengajuan"

        val PREF_ID_PENGAJUAN_ADMIN = "PREF_ID_PENGAJUAN_ADMIN"
        val PREF_ID_MASYARAKAT_ADMIN = "PREF_ID_MASYARAKAT_ADMIN"
        val PREF_NAMA_NASABAH = "PREF_NAMA_NASABAH"
        val PREF_TANGGAL_PENGAJUAN = "PREF_TANGGAL_PENGAJUAN"
        val PREF_NOTE_PENGAJUAN = "PREF_NOTE_PENGAJUAN"
    }
}